### ISSUE TITLE
Cannot update to ver. 4b0d5c6

### ISSUE THREAD

**Issue by amnsharif** [sysofwan/ha-triones#13]
Hi,
I'm unable to update to ver. 4b0d5c6
I receive the following error: "Failed to call service update/install. string index out of range "
Than you for the great efforts

**Comment by gitothy** [comment]
Same here.  I have a strong feeling that an uninstall and re-install of the integration will solve this but not got round to it myself.

![image](https://user-images.githubusercontent.com/39539635/172144064-dba896b8-014f-477c-8c19-68de3e4f1a15.png)

**Comment by amnsharif** [comment]
Yes. This is actually what I did and it worked

**Comment by gitothy** [comment]
Hmmm actually that isn't working for me.  I deleted the integration, uninsalled the old version from HACS and restarted HA.  Validated the directory is gone from custom_components then tried to re-install through HACS.  Same error:
`2022-06-17 17:27:48 ERROR (MainThread) [custom_components.hacs] string index out of range`

![image](https://user-images.githubusercontent.com/39539635/174339103-23c27daa-fb0e-44ac-a542-5f94b6ed826c.png)

I guess a manual install is the next thing to try? Odd that it worked for you @amnsharif. If you don't mind can you confirm exactly what you did to get it working again?

**Comment by amnsharif** [comment]
I hope I remember it right; first I deleted the device from integrations, removed the repository from HACS, made sure no content were in custom_components, then re-added it from HACS and finally wentto integrations and proceeded with the setup

**Comment by gitothy** [comment]
Finally got it installed. Not the poxy thing can't seem to pick up my light. Still works perfectly from the phone app. Oh well! 
Will close this ticket.
