### ISSUE TITLE
Use new HA Bluetooth support 

### ISSUE THREAD

**Issue by amnsharif** [sysofwan/ha-triones#16]
So after updating to HAOS 8.4, the integration no longer works. Tried reinstalling with no luck.
The error message says: "Config flow could not be loaded: undefined"
I noticed with the new update is that a Bluetooth integration has been added. I wonder if Triones should use new config because of the new Bluetooth integration.

**Comment by sysofwan** [comment]
Yes, it should. I don’t have the bandwidth to implement this right now. Will help if anyone wants to look into it.

**Comment by amnsharif** [comment]
Can confirm it's the latest update. I restored to a previous backup and the is working now. 
I'm a total amateur in Python, butI would love to give it a try if you can share the docs/guides you used to implement the integration

**Comment by bartek810** [comment]
Would love if you fix it. I just found your repo yesterday and hoped for this integration.

**Comment by amnsharif** [comment]
So I started looking into this project only to find out that my bluetooth radio is not supported and cannot be detected by Homeassistant. It doesn't seem feasible to buy a new bluetooth device over a new Tuya supported LED strip which can be easily added to HAOS.
If I get my hands on a supported bluetooth device, or it beomes supported by HAOS. I'll definitely work on it.  Apologies 🙏

**Comment by inkpw2** [comment]
I would love to look into this but have no idea where to start. I have time to learn. Could anyone point me in the right direction?

**Comment by amnsharif** [comment]
This topic will be closed as th the new HA brings native support to Triones. It is unnecessary to use this custom integration anymore.
Thanks to the developer for his massive efforts in implementing this. We enjoyed long time of happylighting use 😀
