### ISSUE TITLE
Unable to find my lights - "Triones:"

### ISSUE THREAD

**Issue by heebnerd** [sysofwan/ha-triones#2]
I installed the integration via HACS and then added the component. I was able to get the MAC address of my bluetooth controller (via bluetoothctl) and it appeared to be scanning. It never finds my lights.

However from the bluetoothctl output, it looks like the lights I have start with "Triones:" From the looks of the triones.py scrip tis looking for devices that start with "Triones-". 

Should I'll need to do it alter that script to looks for "Triones:"? Or is there more?

**Comment by sysofwan** [comment]
Thanks for reporting this. I just pushed a fix. Feel free to try it out.
