### ISSUE TITLE
Home Assistant 2021.12.0

### ISSUE THREAD

**Issue by ckd77** [sysofwan/ha-triones#7]
Hi!

After updating home assistant, this error appears in the logs. ;)

> Logger: homeassistant.setup
> Source: setup.py:291
> First occurred: 09:43:32 (1 occurrences)
> Last logged: 09:43:32
> 
> Unable to prepare setup for platform triones.light: Platform not found (cannot import name '_match_max_scale' from 'homeassistant.util.color' (/usr/src/homeassistant/homeassistant/util/color.py)).

**Comment by sysofwan** [comment]
Fixed with latest version

**Comment by ckd77** [comment]
No more errors and everything works fine. Thank you :)
